<div class="photoleft"><img src="images/home-family-broadband.jpg" alt="Broadband Home" /></div>
<h2>Superfast <span class="colour">Home Broadband</span></h2>
<p>Our service uses microwave radio technology.&nbsp; This means our broadband doesn&rsquo;t have the same speed and location restrictions as other broadband companies in rural areas. Once your service is installed there is no line rental.&nbsp;</p>
<p><a class="btn" href="broadband/home/">&gt; Show me more</a></p>
<div class="clearspace">&nbsp;</div>
<div class="photoleft"><img src="images/home-phone.jpg" alt="Home Phone" /></div>
<h2>No line rental <span class="colour">Home Phone Service</span></h2>
<p>As well as a fast broadband service we can provide you with an internet phone service, also known as VoIP (voice over Internet). By adding this to your broadband you&rsquo;ll be able to make cheaper calls.&nbsp;</p>
<p><a class="btn" href="telephony/home/">&gt; Show me more</a></p>
<div class="clearspace">&nbsp;</div>