<h1 class="colour">Case Studies</h1>
<div class="scrollitem">
<div class="photoleft"><img src="images/case-studies-img.png" alt="" /></div>
<div>&nbsp;</div>
<h2>Superfast broadband for guests in the Cartmel Peninsula</h2>
<p>Family owned <a href="http://www.cartmellodgepark.co.uk/">Cartmel Park</a> near Cartmel now offers superfast broadband to their 30 permanent holiday lodge owners and 30 visiting caravans. &ldquo;Everyone now gets fast, reliable broadband with Kencomp&rsquo;s microwave broadband service.&rsquo; said owner Zarina Cretney. &ldquo;And to ensure the broadband is shared equally among all our guests Kencomp installed an easy to use secure Wi-Fi network with a hotspot&rdquo; she added.&nbsp; If you run a holiday park or hotel and would like to improve your broadband and Wi-Fi, please contact us.</p>
</div>