<div class="searchpanel2">
<div class="corner">&nbsp;</div>
<div class="side">&nbsp;</div>
<div class="h1"><strong>Can I get <em>Superfast</em> Broadband?</strong></div>
<p>Enter your postcode below to see if you can receive superfast broadband from us.</p>
<form id="checkarea" action="coverage/" method="get"><input id="postcode" class="postcodefield" type="text" name="postcode" /><input class="btn" type="submit" value="&gt; Check area" /></form></div>