<div class="photoleft"><img src="images/home-broadband.jpg" alt="Broadband Home" /></div>
<h2>Superfast <span class="colour">Home Broadband</span></h2>
<p>Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt.</p>
<p><a href="broadband/home/" class="btn">&gt; Show me more</a></p>
<div class="clearspace">&nbsp;</div>

<div class="photoleft"><img src="images/business-broadband.jpg" alt="Broadband Business" /></div>
<h2>Superfast <span class="colour">Business Broadband</span></h2>
<p>Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt.</p>
<p><a href="broadband/business/" class="btn">&gt; Show me more</a></p>
<div class="clearspace">&nbsp;</div>

<div class="photoleft"><img src="images/corporate-broadband.jpg" alt="Corporate Broadband" /></div>
<h2>Superfast <span class="colour">Corporate Broadband</span></h2>
<p>Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt.</p>
<p><a href="broadband/corporate/" class="btn">&gt; Show me more</a></p>
<div class="clearspace">&nbsp;</div>

<div class="photoleft"><img src="images/community-broadband.jpg" alt="Community Broadband" /></div>
<h2>Superfast <span class="colour">Community Broadband</span></h2>
<p>Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt.</p>
<p><a href="broadband/community/" class="btn">&gt; Show me more</a></p>
<div class="clearspace">&nbsp;</div>

<div class="photoleft"><img src="images/broadband-caravan.jpg" alt="Caravan Broadband" /></div>
<h2>Superfast Broadband for <span class="colour">Caravan Parks</span></h2>
<p>Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt.</p>
<p><a href="broadband/holiday-parks/" class="btn">&gt; Show me more</a></p>
<div class="clearspace">&nbsp;</div>