<div class="photoleft"><img src="images/home-telephony.jpg" alt="Telephony Home" /></div>
<h2>Home <span class="colour">Telephony</span></h2>
<p>Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt.</p>
<p><a href="telephony/home/" class="btn">&gt; Show me more</a></p>
<div class="clearspace">&nbsp;</div>

<div class="photoleft"><img src="images/business-telephony.jpg" alt="Telephony Business" /></div>
<h2>Business <span class="colour">Telephony</span></h2>
<p>Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt.</p>
<p><a href="telephony/business/" class="btn">&gt; Show me more</a></p>
<div class="clearspace">&nbsp;</div>

<div class="photoleft"><img src="images/hotels-telephony.jpg" alt="Telephony Hotels" /></div>
<h2>Hotels <span class="colour">Telephony</span></h2>
<p>Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt.</p>
<p><a href="telephony/hotels/" class="btn">&gt; Show me more</a></p>
<div class="clearspace">&nbsp;</div>

<div class="photoleft"><img src="images/holiday-parks-telephony.jpg" alt="Telephony Holiday Parks" /></div>
<h2>Holiday Parks <span class="colour">Telephony</span></h2>
<p>Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt.</p>
<p><a href="telephony/holiday-parks/" class="btn">&gt; Show me more</a></p>
<div class="clearspace">&nbsp;</div>