<div id="header_flash">
	<div id="header_flash_alternate">
		<p><strong>Upgrade Flash Player</strong> <a href="http://www.adobe.com/go/getflashplayer">Download Adobe Flash Player to view the slideshow</a></p>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
var flashvars = {
	xmlSource:"content.xml",
	fv_r:"false", /* random true/false */
	fv_w:"676", /* Photo Width */
	fv_h:"325", /* Photo Height */
	fv_x:"0", /* Offset X  */
	fv_y:"0", /* Offset Y */
	fv_time:"5", /* 3,4,5,6,7,8,9,10 */
	fv_trans:"1", /* 1+ */
	fv_xpad:"8", /* Padding X */
	fv_ypad:"8", /* Padding Y */
	fv_helper:"true", /* true/false */
	fv_helperAlign:"topRight", /* topLeft, topRight, bottomLeft, bottomRight */
	fv_caption:"true", /* true/false */
	fv_captionAlign:"bottomLeft" /* topLeft, topCenter, topRight, bottomLeft, bottomCenter, bottomRight */
};
var params = { base:"flash/header/generic/", wmode:"transparent" };
swfobject.embedSWF("flash/header/header.swf", "header_flash", "676", "325", "8.0.0", "flash/expressInstall.swf", flashvars, params, false);
//]]>
</script>
