<div class="contact_item"><strong>Sales:</strong> sales@kencomp.net</div>
<div class="contact_item"><strong>Support:</strong> support@kencomp.net</div>
<div class="contact_item"><strong>Call us today:</strong> 01539 898 145</div>
<div class="clear">&nbsp;</div>
<p>Kencomp Internet Limited,&nbsp;Unit 1, Meadowbank Business Park, Shap Road, Kendal, LA9 6NY</p>
<p><a class="btn" href="enquiries/">&gt; Get Directions</a></p>