<div class="searchpanel">
				<div class="corner">&nbsp;</div>
				<div class="side">&nbsp;</div>
				<div class="h1"><strong>Can I get <em>Superfast</em> Broadband?</strong></div>
				<p>Enter your postcode below to see if you can receive superfast broadband from us.</p>
				<form action="coverage/" id="checkarea" method="get"><input id="postcode" name="postcode" class="postcodefield" /><input type="submit" value="&gt; Check area" class="btn" /></form>
			</div>