<div class="photoleft"><img src="images/business-user-broadband.jpg" alt="Broadband Business" /></div>
<h2>Superfast <span class="colour">Business Broadband</span></h2>
<p>Our broadband works without phone lines so it doesn&rsquo;t have the same speed restrictions many other broadband companies have in rural areas.&nbsp;We have service plans that fit the needs of all types of Cumbrian businesses. &nbsp;</p>
<p><a class="btn" href="broadband/business/">&gt; Show me more</a></p>
<div class="clearspace">&nbsp;</div>
<div class="photoleft"><img src="images/business-user-telephony.jpg" alt="Business Telephony" /></div>
<h2>21st Century <span class="colour">Telephony</span></h2>
<p>We can provide your business with an internet phone service. Using state of the art technology we can provide you with a fully featured phone system at a fraction of the cost of a traditional phone system.</p>
<p><a class="btn" href="telephony/business/">&gt; Show me more</a></p>
<div class="clearspace">&nbsp;</div>
<div class="photoleft"><img src="images/corporate-user-broadband.jpg" alt="Corporate Broadband" /></div>
<h2>Superfast <span class="colour">Corporate Broadband</span></h2>
<p>Our highly skilled network engineers can apply our technology to deliver bespoke solutions for your business. We can provide superfast connectivity, inter-site links and wide area networks tailored to your needs.</p>
<p><a class="btn" href="broadband/corporate/">&gt; Show me more</a></p>
<div class="clearspace">&nbsp;</div>