<div class="photoleft"><img src="images/hotel-wifi.jpg" alt="Hotel Wi-Fi" /></div>
<h2>Hotel <span class="colour">Wifi</span></h2>
<p>Wireless is no longer just another amenity at hotels, to go along with a nice meal and an away-day break. Business travel, meeting rooms and conferences are all part of life for today&rsquo;s business person &ndash; if a hotel doesn&rsquo;t have &ldquo;good and reliable&rdquo; Wi-Fi then the user doesn&rsquo;t go back, he looks elsewhere.</p>
<p><a class="btn" href="wi-fi/hotels/">&gt; Show me more</a></p>
<div class="clearspace">&nbsp;</div>
<div class="photoleft"><img src="images/caravan-wifi.jpg" alt="Caravan Wi-Fi" /></div>
<h2>Caravan Park <span class="colour">Wifi</span></h2>
<p>Providing an additional service such as internet access and phone services in each lodge at your caravan, camping or holiday park can give you a competitive advantage over other leisure businesses in your area and can earn you money.</p>
<p><a class="btn" href="wi-fi/holiday-parks/">&gt; Show me more</a></p>
<div class="clearspace">&nbsp;</div>
<div class="photoleft"><img src="images/caravan-wifi.jpg" alt="Caravan Wi-Fi" /></div>
<h2>Holiday Lets <span class="colour">Wifi</span></h2>
<p>We have helped many landlords provide Wi-Fi to tenants with peace of mind. Our hotspot solution enables remote management of multiple properties with multiple tenants. This reduces the risk of unlawful internet usage on our landlord&rsquo;s account and eradicates excess usage charges. For those landlords who want to earn a return on their investment in Wi-Fi we can provide a combination of free and paid for Wi-Fi access which is easy to manage.</p>
<p><a class="btn" href="wi-fi/holiday-lets/">&gt; Show me more</a></p>
<div class="clearspace">&nbsp;</div>