<p class="h2" style="line-height: 8px; text-align: center; color: red;" align="center">&nbsp;</p>
<p class="smalltext" style="line-height: 8px; text-align: center; color: red;" align="center"><strong><span style="color: #000000; font-size: 1.35em;">Why wait? Get a gigabit connection today</span></strong></p>
<p class="smalltext" style="line-height: 15px; text-align: center; color: #14b9d6;" align="center"><span style="color: #14b9d6; font-size: 1.65em;"><img src="images/gigabit_bar.png" alt="" width="307" height="15" /></span></p>
<p class="h2" style="line-height: 15px; text-align: center; color: #14b9d6; font-size: 2.2em;" align="center"><br />The Gift of Gigabit</p>
<p class="h2" style="line-height: 15px; text-align: center; color: red;" align="center"><br /><img src="images/gigabit_bar.png" alt="" width="307" height="15" /></p>
<p class="h2" style="line-height: 8px; text-align: center; color: red;" align="center">&nbsp;</p>
<p class="h2" style="line-height: 8px; text-align: center; color: red;" align="center"><img src="images/gigabit_pre.png" alt="present" width="309" height="274" /></p>
<p class="h2" style="line-height: 8px; text-align: center; color: red;" align="center">&nbsp;</p>
<p class="MsoNormal" style="line-height: 8px; text-align: center; color: red;" align="center">&nbsp;</p>
<p class="MsoNormal" style="line-height: 8px; text-align: center; color: red;" align="center">&nbsp;</p>
<p class="MsoNormal" style="line-height: 8px; text-align: center; color: red;" align="center">&nbsp;</p>
<p class="MsoNormal" style="line-height: 8px; text-align: center; color: red;" align="center"><strong><span style="color: #14b9d6; font-size: 1.65em;">Does Your Business Qualify?</span></strong></p>
<p align="center">Call now on 01539 898 145 <br />or <br />Email us at <a href="mailto:Gigabit@kencomp.net">Gigabit@kencomp.net</a></p>
<p align="center"><input class="btn" onclick="javascript:window.open('https://gigabitvoucher.culture.gov.uk', '_blank');" type="submit" value="&gt; More on Gigabit Scheme" /></p>