<div class="searchpanel">
<div class="corner">&nbsp;</div>
<div class="side">&nbsp;</div>
<div class="h1"><strong>Can I get <em>Superfast</em> Broadband?</strong></div>
<p>Enter your postcode below to see if you can receive superfast broadband from us.</p>
<form id="checkarea" action="coverage/" method="get">
<p><input id="postcode" class="postcodefield" type="text" name="postcode" /><input class="btn" type="submit" value="&gt; Check area" /></p>
</form></div>
<div class="side">
<table style="height: 444px; width: 282px;" border="0" cellspacing="0" cellpadding="0" align="right">
<tbody>
<tr>
<td>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><img style="display: block; margin-left: auto; margin-right: auto;" title="3CX Mobile Apps" src="images/3CX-mobile-apps.png" alt="3CX Mobile Apps" width="232" height="350" />&nbsp; &nbsp;</p>
</td>
</tr>
<tr>
<td style="text-align: center;">
<p><img title="3CX Advanced Certified Engineer" src="http://kencomp.net/images/3CX-advanced-certified-badge.png" alt="Kencomp engineers have Advanced 3CX Certification" width="90" height="90" /></p>
<p>Kencomp Internet engineers have Advanced 3CX Certification</p>
</td>
</tr>
</tbody>
</table>
</div>