<h1><strong class="colour">Contact us</strong></h1>
<p><strong class="colour">Kencomp</strong> <br />Unit 1<br />Meadowbank Business Park<br />Shap Road<br />Kendal<br />LA9 6NY</p>
<p><strong class="colour">by phone</strong> on 01539 898145 <br /><strong class="colour">by email</strong> sales@kencomp.net</p>
<p>If emailing or using the form below, we will respond within 24 hours.</p>
<div class="clearspace">&nbsp;</div>
<div class="clearspace">&nbsp;</div>
<div id="dirctions">&nbsp;</div>